def generate_html():
    """Function that returns the HTML content"""
    from html import escape

    return """\
<!DOCTYPE html>\n"
        "<html lang=\"zh-Hant\">\n"
        "<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>龍運巴士機場地面運輸中心顯示屏模擬器 LWB GTC PIDS Simulator</title>\n"
        "  <style>\n"
        "    :root {\n"
        "      --orange: #f36c21;\n"
        "      --blue: #0b3c75;\n"
        "      --white: #ffffff;\n"
        "      --black: #000000;\n"
        "      --border-gray: #c5d3df;\n"
        "    }\n"
        "\n"
        "    * { \n"
        "      box-sizing: border-box; \n"
        "      margin: 0; \n"
        "      padding: 0; \n"
        "      font-family: \"PingFang HK\", \"Microsoft JhengHei\", \"Noto Sans TC\", Arial, sans-serif; \n"
        "      user-select: none;\n"
        "    }\n"
        "\n"
        "    html, body { \n"
        "      width: 100vw;\n"
        "      height: 100vh;\n"
        "      overflow: hidden;\n"
        "      background-color: var(--white);\n"
        "    }\n"
        "\n"
        "    .display-screen {\n"
        "      width: 100vw;\n"
        "      height: 100vh;\n"
        "      background-color: var(--white);\n"
        "      display: flex;\n"
        "      flex-direction: column;\n"
        "    }\n"
        "\n"
        "    .clock-bar {\n"
        "      display: grid;\n"
        "      grid-template-columns: repeat(3, 1fr);\n"
        "      gap: 1.5px; \n"
        "      background-color: var(--white); \n"
        "      min-height: 14vh; \n"
        "    }\n"
        "\n"
        "    .clock-empty { background-color: var(--white); }\n"
        "\n"
        "    /* 更新：時鐘容器移至第三欄左側，內部文字互相比例置中 */\n"
        "    .clock-wrapper {\n"
        "      grid-column: 3;\n"
        "      background-color: var(--white);\n"
        "      display: flex;\n"
        "      flex-direction: column;\n"
        "      justify-content: center;\n"
        "      align-items: center; /* 讓時間 XX:XX 於標題下方置中 */\n"
        "      justify-self: flex-start; /* 將整個區塊對齊到第三欄的最左邊 */\n"
        "      padding-left: 1.5vw; /* 稍微留點空間，不讓文字死貼框線 */\n"
        "    }\n"
        "\n"
        "    .clock-title {\n"
        "      font-size: clamp(16px, 2.2vh, 26px);\n"
        "      font-weight: 700;\n"
        "      color: var(--orange);\n"
        "      line-height: 1.2;\n"
        "      margin-bottom: 0.5vh; \n"
        "      text-align: center;\n"
        "    }\n"
        "\n"
        "    .clock-time {\n"
        "      font-size: clamp(45px, 7vh, 85px); \n"
        "      font-weight: 900;\n"
        "      color: var(--orange);\n"
        "      line-height: 1;\n"
        "      text-align: center;\n"
        "    }\n"
        "\n"
        "    .grid-wrapper {\n"
        "      flex: 1;\n"
        "      display: flex;\n"
        "      flex-direction: column;\n"
        "      background-color: var(--border-gray);\n"
        "    }\n"
        "\n"
        "    .eta-header-bar {\n"
        "      display: grid;\n"
        "      grid-template-columns: repeat(3, 1fr);\n"
        "      gap: 1.5px; \n"
        "      background-color: var(--border-gray);\n"
        "    }\n"
        "\n"
        "    .eta-header-bar div {\n"
        "      background-color: var(--orange);\n"
        "      color: var(--white);\n"
        "      font-weight: bold;\n"
        "      font-size: clamp(12px, 1.8vh, 22px);\n"
        "      height: 4vh;\n"
        "      display: flex;\n"
        "      align-items: center;\n"
        "      justify-content: flex-end;\n"
        "      padding-right: 1.5vw;\n"
        "    }\n"
        "\n"
        "    .grid-container {\n"
        "      flex: 1;\n"
        "      display: grid;\n"
        "      grid-template-columns: repeat(3, 1fr);\n"
        "      grid-template-rows: repeat(5, 1fr); \n"
        "      background-color: var(--border-gray);\n"
        "      gap: 1.5px;\n"
        "    }\n"
        "\n"
        "    .cell {\n"
        "      background-color: var(--white);\n"
        "      display: flex;\n"
        "      justify-content: space-between;\n"
        "      align-items: flex-start;\n"
        "      padding: 0.5vh 0.8vw; \n"
        "    }\n"
        "\n"
        "    .left-col {\n"
        "      display: flex;\n"
        "      flex-direction: column;\n"
        "      justify-content: flex-start;\n"
        "      gap: 0vh;\n"
        "    }\n"
        "\n"
        "    .route-num { \n"
        "      font-size: clamp(45px, 7.2vh, 95px); \n"
        "      font-weight: 900; \n"
        "      color: var(--black); \n"
        "      line-height: 0.85;\n"
        "      letter-spacing: -1px;\n"
        "    }\n"
        "\n"
        "    .route-dest { \n"
        "      display: flex;\n"
        "      flex-direction: column;\n"
        "      justify-content: center;\n"
        "      margin-top: 0.5vh;\n"
        "    }\n"
        "\n"
        "    .dest-zh {\n"
        "      font-size: clamp(16px, 2.4vh, 32px);\n"
        "      font-weight: 800;\n"
        "      color: var(--black);\n"
        "      line-height: 1.1;\n"
        "    }\n"
        "\n"
        "    .dest-en {\n"
        "      font-size: clamp(11px, 1.4vh, 18px);\n"
        "      font-weight: 700;\n"
        "      color: #555;\n"
        "      text-transform: uppercase;\n"
        "      line-height: 1;\n"
        "    }\n"
        "\n"
        "    .route-eta { \n"
        "      font-size: clamp(45px, 7.2vh, 95px); \n"
        "      font-weight: 900; \n"
        "      color: var(--blue); \n"
        "      text-align: right; \n"
        "      line-height: 0.85;\n"
        "      letter-spacing: 0.5px;\n"
        "      align-self: flex-start; \n"
        "    }\n"
        "\n"
        "    .loading-msg {\n"
        "      grid-column: 1/4; \n"
        "      text-align: center; \n"
        "      font-size: clamp(24px, 4vh, 40px); \n"
        "      padding-top: 5vh; \n"
        "      font-weight: bold; \n"
        "      color: var(--blue);\n"
        "    }\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "\n"
        "  <div class=\"display-screen\" id=\"screen\">\n"
        "    <div class=\"clock-bar\">\n"
        "      <div class=\"clock-empty\"></div>\n"
        "      <div class=\"clock-empty\"></div>\n"
        "      <!-- 時鐘區塊 -->\n"
        "      <div class=\"clock-wrapper\">\n"
        "        <div class=\"clock-title\">現在時間 Current Time :</div>\n"
        "        <div class=\"clock-time\" id=\"currentTime\">--:--</div>\n"
        "      </div>\n"
        "    </div>\n"
        "\n"
        "    <div class=\"grid-wrapper\">\n"
        "      <div class=\"eta-header-bar\">\n"
        "        <div>預計時間 ETA</div>\n"
        "        <div>預計時間 ETA</div>\n"
        "        <div>預計時間 ETA</div>\n"
        "      </div>\n"
        "      <div class=\"grid-container\" id=\"routeGrid\">\n"
        "        <div class=\"loading-msg\">🔄 正在連線至九巴系統載入即時班次...</div>\n"
        "      </div>\n"
        "    </div>\n"
        "  </div>\n"
        "\n"
        "  <script>\n"
        "    const ITEMS_PER_PAGE = 15; \n"
        "\n"
        "    const fallbackList = [\n"
        "      { route: \"A30\", destZh: \"往 梨木樹\", destEn: \"TO LEI MUK SHUE\" },\n"
        "      { route: \"A31\", destZh: \"往 荃灣(如心廣場)\", destEn: \"TO TSUEN WAN (NINA TOWER)\" },\n"
        "      { route: \"A32\", destZh: \"往 葵涌邨\", destEn: \"TO KWAI CHUNG ESTATE\" },\n"
        "      { route: \"A33\", destZh: \"往 屯門公路轉車站\", destEn: \"TO TUEN MUN ROAD BBI\" },\n"
        "      { route: \"A34\", destZh: \"往 洪水橋(洪元路)\", destEn: \"TO HUNG SHUI KIU (HUNG YUEN ROAD)\" },\n"
        "      { route: \"A36\", destZh: \"往 錦上路站\", destEn: \"TO KAM SHEUNG ROAD STATION\" },\n"
        "      { route: \"A38\", destZh: \"往 荃灣(荃威花園)\", destEn: \"TO TSUEN WAN (ALLWAY GARDENS)\" },\n"
        "      { route: \"A41\", destZh: \"往 碩門邨\", destEn: \"TO SHEK MUN ESTATE\" },\n"
        "      { route: \"A41P\", destZh: \"往 烏溪沙站\", destEn: \"TO WU KAI SHA STATION\" },\n"
        "      { route: \"A42\", destZh: \"往 黃泥頭\", destEn: \"TO WONG NAI TAU\" },\n"
        "      { route: \"A43\", destZh: \"往 粉嶺(聯和墟)\", destEn: \"TO FANLING (LUEN WO HUI)\" },\n"
        "      { route: \"A43P\", destZh: \"往 粉嶺(聯和墟)\", destEn: \"TO FANLING (LUEN WO HUI)\" },\n"
        "      { route: \"A46\", destZh: \"往 火炭(駿景園)\", destEn: \"TO FO TAN (ROYAL ASCOT)\" },\n"
        "      { route: \"A47X\", destZh: \"往 大埔(太和)\", destEn: \"TO TAI PO (TAI WO)\" },\n"
        "      { route: \"E32\", destZh: \"往 葵芳(南)\", destEn: \"TO KWAI FONG (SOUTH)\" },\n"
        "      { route: \"E33\", destZh: \"往 屯門市中心\", destEn: \"TO TUEN MUN CENTRAL\" },\n"
        "      { route: \"E36\", destZh: \"往 元朗(八鄉路)\", destEn: \"TO YUEN LONG (PAT HEUNG ROAD)\" },\n"
        "      { route: \"E37\", destZh: \"往 天水圍市中心\", destEn: \"TO TIN SHUI WAI TOWN CENTRE\" },\n"
        "      { route: \"E41\", destZh: \"往 大埔頭\", destEn: \"TO TAI PO TAU\" },\n"
        "      { route: \"E42\", destZh: \"往 沙田(博康)\", destEn: \"TO SHA TIN (POK HONG)\" }\n"
        "    ];\n"
        "\n"
        "    let routesData = [];\n"
        "    let currentPage = 0;\n"
        "    let gtcStopIds = []; \n"
        "\n"
        "    function updateClock() {\n"
        "      const now = new Date();\n"
        "      document.getElementById(\'currentTime\').textContent = \n"
        "        `${String(now.getHours()).padStart(2, \'0\')}:${String(now.getMinutes()).padStart(2, \'0\')}`;\n"
        "    }\n"
        "\n"
        "    function formatTime(etaStr) {\n"
        "      if (!etaStr) return \"-\";\n"
        "      const d = new Date(etaStr);\n"
        "      if (isNaN(d.getTime())) return \"-\";\n"
        "      return `${String(d.getHours()).padStart(2, \'0\')}:${String(d.getMinutes()).padStart(2, \'0\')}`;\n"
        "    }\n"
        "\n"
        "    async function initGtcStopIds() {\n"
        "      const cachedIds = localStorage.getItem(\'gtc_stop_ids_v1\');\n"
        "      if (cachedIds) {\n"
        "        gtcStopIds = JSON.parse(cachedIds);\n"
        "        return; \n"
        "      }\n"
        "\n"
        "      try {\n"
        "        document.getElementById(\'routeGrid\').innerHTML = `<div class=\"loading-msg\">🔄 系統首次初始化 (尋找機場站點中)，請稍候幾秒鐘...</div>`;\n"
        "        const res = await fetch(\"https://data.etabus.gov.hk/v1/transport/kmb/stop\");\n"
        "        const json = await res.json();\n"
        "        if (json && Array.isArray(json.data)) {\n"
        "          const stops = json.data.filter(s => s.name_tc && s.name_tc.includes(\"地面運輸中心\"));\n"
        "          gtcStopIds = [...new Set(stops.map(s => s.stop))];\n"
        "          localStorage.setItem(\'gtc_stop_ids_v1\', JSON.stringify(gtcStopIds)); \n"
        "        }\n"
        "      } catch (err) {\n"
        "        console.error(\"無法取得站點清單\", err);\n"
        "      }\n"
        "    }\n"
        "\n"
        "    async function fetchData() {\n"
        "      try {\n"
        "        if (gtcStopIds.length === 0) {\n"
        "          await initGtcStopIds();\n"
        "        }\n"
        "\n"
        "        if (gtcStopIds.length === 0) return;\n"
        "\n"
        "        const nowMs = Date.now() - 60000; \n"
        "        const map = new Map();\n"
        "        const allowedRoutes = new Set(fallbackList.map(r => r.route));\n"
        "        \n"
        "        let allData = [];\n"
        "        let hasSuccess = false;\n"
        "\n"
        "        const promises = gtcStopIds.map(id => \n"
        "          fetch(`https://data.etabus.gov.hk/v1/transport/kmb/stop-eta/${id}?_t=${Date.now()}`)\n"
        "          .then(r => r.json())\n"
        "          .catch(() => null)\n"
        "        );\n"
        "        const results = await Promise.all(promises);\n"
        "        \n"
        "        results.forEach(res => {\n"
        "          if (res && Array.isArray(res.data)) {\n"
        "            allData.push(...res.data);\n"
        "            hasSuccess = true;\n"
        "          }\n"
        "        });\n"
        "\n"
        "        if (hasSuccess) {\n"
        "          allData.forEach(item => {\n"
        "            if (allowedRoutes.has(item.route) && item.eta && !item.dest_tc.includes(\"機場\")) {\n"
        "              const etaMs = new Date(item.eta).getTime();\n"
        "              if (!isNaN(etaMs) && etaMs >= nowMs) {\n"
        "                if (!map.has(item.route) || etaMs < map.get(item.route).rawTime) {\n"
        "                  map.set(item.route, {\n"
        "                    route: item.route,\n"
        "                    destZh: `往 ${item.dest_tc || \'\'}`,\n"
        "                    destEn: `TO ${item.dest_en ? item.dest_en.toUpperCase() : \'\'}`,\n"
        "                    eta: formatTime(item.eta),\n"
        "                    rawTime: etaMs\n"
        "                  });\n"
        "                }\n"
        "              }\n"
        "            }\n"
        "          });\n"
        "\n"
        "          if (map.size > 0) {\n"
        "            routesData = Array.from(map.values()).sort((a, b) =>\n"
        "              a.route.localeCompare(b.route, \'en\', { numeric: true, sensitivity: \'base\' })\n"
        "            );\n"
        "          } else {\n"
        "            routesData = [];\n"
        "          }\n"
        "          \n"
        "          renderPage(currentPage);\n"
        "        }\n"
        "      } catch (err) {\n"
        "        console.error(\"API 處理異常:\", err);\n"
        "      }\n"
        "    }\n"
        "\n"
        "    function renderPage(pageIndex) {\n"
        "      const grid = document.getElementById(\'routeGrid\');\n"
        "      \n"
        "      if (routesData.length === 0) {\n"
        "        grid.innerHTML = `<div class=\"loading-msg\" style=\"color: #666;\">目前時段暫無班次資料</div>`;\n"
        "        return;\n"
        "      }\n"
        "\n"
        "      const totalPages = Math.ceil(routesData.length / ITEMS_PER_PAGE) || 1;\n"
        "      currentPage = pageIndex % totalPages;\n"
        "      if (currentPage < 0) currentPage = totalPages - 1;\n"
        "\n"
        "      grid.innerHTML = \'\';\n"
        "      const startIndex = currentPage * ITEMS_PER_PAGE;\n"
        "      const pageItems = routesData.slice(startIndex, startIndex + ITEMS_PER_PAGE);\n"
        "\n"
        "      for (let i = 0; i < ITEMS_PER_PAGE; i++) {\n"
        "        const item = pageItems[i];\n"
        "        const cell = document.createElement(\'div\');\n"
        "        cell.className = \'cell\';\n"
        "\n"
        "        if (item) {\n"
        "          cell.innerHTML = `\n"
        "            <div class=\"left-col\">\n"
        "              <div class=\"route-num\">${item.route}</div>\n"
        "              <div class=\"route-dest\">\n"
        "                <div class=\"dest-zh\">${item.destZh}</div>\n"
        "                <div class=\"dest-en\">${item.destEn}</div>\n"
        "              </div>\n"
        "            </div>\n"
        "            <div class=\"route-eta\">${item.eta}</div>\n"
        "          `;\n"
        "        }\n"
        "        grid.appendChild(cell);\n"
        "      }\n"
        "    }\n"
        "\n"
        "    document.addEventListener(\'dblclick\', () => {\n"
        "      if (!document.fullscreenElement) document.documentElement.requestFullscreen().catch(() => {});\n"
        "      else document.exitFullscreen().catch(() => {});\n"
        "    });\n"
        "\n"
        "    updateClock();\n"
        "    setInterval(updateClock, 1000);\n"
        "\n"
        "    fetchData(); \n"
        "    setInterval(fetchData, 15000); \n"
        "    setInterval(() => {\n"
        "      if (routesData.length > 0) renderPage(currentPage + 1);\n"
        "    }, 10000); \n"
        "  </script>\n"
        "</body>\n"
        "</html>"""

if __name__ == "__main__":
    html = generate_html()
    print(html)
    # You can also write to a file:
    # with open("output.html", "w") as f:
    #     f.write(html)
